# Generated by Django 4.2.7 on 2023-11-03 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digi_save_vsla_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentinfo',
            old_name='group_id',
            new_name='group',
        ),
    ]
