# Generated by Django 4.2.7 on 2023-11-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi_save_vsla_api', '0002_rename_group_id_paymentinfo_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='next_of_kin_phone_number',
            field=models.TextField(null=True),
        ),
    ]
