# Generated by Django 4.2.7 on 2023-11-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi_save_vsla_api', '0003_alter_users_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='next_of_kin_phone_number',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
