# Generated by Django 4.2.7 on 2023-11-06 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digi_save_vsla_api', '0005_activecyclemeeting_sync_flag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constitutiontable',
            name='frequencyOfContributions',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='constitutiontable',
            name='group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digi_save_vsla_api.groupprofile'),
        ),
        migrations.AlterField(
            model_name='constitutiontable',
            name='hasConstitution',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='constitutiontable',
            name='interestMethod',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='constitutiontable',
            name='loanTerms',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='constitutiontable',
            name='offersLoans',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='constitutiontable',
            name='registrationFee',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='constitutiontable',
            name='selectedCollateralRequirements',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='constitutiontable',
            name='sync_flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='constitutiontable',
            name='usesGroupShares',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='numberOfMeetings',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
