# Generated by Django 4.2.7 on 2023-11-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi_save_vsla_api', '0006_alter_constitutiontable_frequencyofcontributions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupprofile',
            name='countryOfOrigin',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='groupLogoPath',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='groupName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='groupStatus',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='loanFund',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='meetingLocation',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='numberOfCycles',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='numberOfMeetings',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='partnerID',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='socialFund',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='sync_flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='workingWithPartner',
            field=models.CharField(max_length=255),
        ),
    ]
