# Generated by Django 4.2.7 on 2023-11-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi_save_vsla_api', '0008_alter_constitutiontable_hasconstitution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constitutiontable',
            name='hasConstitution',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
