# Generated by Django 4.2.7 on 2023-11-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi_save_vsla_api', '0009_alter_constitutiontable_hasconstitution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constitutiontable',
            name='hasConstitution',
            field=models.BooleanField(default=False),
        ),
    ]
