# Generated by Django 4.2.7 on 2023-11-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi_save_vsla_api', '0011_alter_constitutiontable_hasconstitution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constitutiontable',
            name='frequencyOfContributions',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
