# Generated by Django 4.2.7 on 2023-11-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi_save_vsla_api', '0012_alter_constitutiontable_frequencyofcontributions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupprofile',
            name='countryOfOrigin',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='groupLogoPath',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='groupStatus',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='isWorkingWithPartner',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='loanFund',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='meetingLocation',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='socialFund',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='workingWithPartner',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
