# Generated by Django 4.2.7 on 2023-11-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi_save_vsla_api', '0014_alter_groupprofile_groupname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='sync_flag',
            field=models.IntegerField(default=0),
        ),
    ]
