# Generated by Django 4.2.7 on 2023-11-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi_save_vsla_api', '0015_alter_users_sync_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='next_of_kin_has_phone_number',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='pwd_type',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
