# Generated by Django 4.2.7 on 2023-11-06 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digi_save_vsla_api', '0016_alter_users_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cycleschedules',
            old_name='group',
            new_name='group_id',
        ),
    ]
