# Generated by Django 4.2.7 on 2023-11-06 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digi_save_vsla_api', '0017_rename_group_cycleschedules_group_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmembers',
            old_name='group',
            new_name='group_id',
        ),
    ]
