# Generated by Django 4.2.7 on 2023-11-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi_save_vsla_api', '0018_rename_group_groupmembers_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmembers',
            name='sync_flag',
            field=models.IntegerField(default=0),
        ),
    ]
