# Generated by Django 4.2.7 on 2023-11-06 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digi_save_vsla_api', '0019_alter_groupmembers_sync_flag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmembers',
            old_name='users',
            new_name='user_id',
        ),
    ]
