# Generated by Django 4.2.7 on 2023-11-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi_save_vsla_api', '0020_rename_users_groupmembers_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignedpositions',
            old_name='group',
            new_name='group_id',
        ),
        migrations.RenameField(
            model_name='assignedpositions',
            old_name='member',
            new_name='member_id',
        ),
        migrations.RenameField(
            model_name='assignedpositions',
            old_name='position',
            new_name='position_id',
        ),
        migrations.AlterField(
            model_name='positions',
            name='sync_flag',
            field=models.IntegerField(default=0),
        ),
    ]
