# Generated by Django 4.2.7 on 2023-11-07 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digi_save_vsla_api', '0021_rename_group_assignedpositions_group_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupform',
            old_name='assigned_position',
            new_name='assigned_position_id',
        ),
        migrations.RenameField(
            model_name='groupform',
            old_name='constitution',
            new_name='constitution_id',
        ),
        migrations.RenameField(
            model_name='groupform',
            old_name='cycle_schedule',
            new_name='cycle_schedule_id',
        ),
        migrations.RenameField(
            model_name='groupform',
            old_name='group_member',
            new_name='group_member_id',
        ),
        migrations.RenameField(
            model_name='groupform',
            old_name='group_profile',
            new_name='group_profile_id',
        ),
        migrations.AlterField(
            model_name='assignedpositions',
            name='sync_flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='groupform',
            name='group_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='groupform',
            name='logged_in_users_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digi_save_vsla_api.users'),
        ),
        migrations.AlterField(
            model_name='groupform',
            name='sync_flag',
            field=models.IntegerField(default=0),
        ),
    ]
