# Generated by Django 4.2.7 on 2023-11-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi_save_vsla_api', '0022_rename_assigned_position_groupform_assigned_position_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedpositions',
            name='position_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
