# Generated by Django 4.2.7 on 2023-11-07 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digi_save_vsla_api', '0023_alter_assignedpositions_position_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershares',
            name='cyclemeeting',
        ),
        migrations.RemoveField(
            model_name='savingsaccount',
            name='users',
        ),
        migrations.RemoveField(
            model_name='welfareaccount',
            name='users',
        ),
        migrations.AddField(
            model_name='membershares',
            name='group_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='digi_save_vsla_api.groupform'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cyclemeeting',
            name='sync_flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fines',
            name='sync_flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='groupcyclestatus',
            name='sync_flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='membershares',
            name='cycle_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digi_save_vsla_api.cyclemeeting'),
        ),
        migrations.AlterField(
            model_name='savingsaccount',
            name='logged_in_users_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digi_save_vsla_api.users'),
        ),
        migrations.AlterField(
            model_name='welfareaccount',
            name='logged_in_users_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digi_save_vsla_api.users'),
        ),
    ]
